config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/show'
  get 'users/new'
  root 'static_page#home'

  get '/new' => 'la_page_secrete#new'
  post '/form_tag' => 'la_page_secrete#create'
  #get '/form_tag' => 'la_page_secrete'
#post '/form_tag' => 'user#tag_create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   get  '/help',    to: 'la_page_secrete#help'
   get  '/about',   to: 'la_page_secrete#about'
   get  '/contact', to: 'la_page_secrete#contact'
   get  '/signup',  to: 'users#new'
   post '/signup',   to: 'users#create'
   get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/question',  to: 'static_page#question'
  get '/reponse', to: 'static_page#reponse'

   resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

    before_save { self.email = email.downcase }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }

    # Returns the hash digest of the given string.
    def User.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/la_page_secrete_controller.rb
class LaPageSecreteController < ApplicationController
  def new
  end

  def create
    puts params
		@user = User.new({
			email: params[:email],
			password: params[:password]
		})
		#render :error, template: 'user/error' unless @user.save
	end
  def error
  end
  def destroy
    @user =User.destroy
  end
end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        log_in user
        redirect_to user
      else
        flash.now[:danger] = 'Invalid email/password combination'
        render 'new'
      end
    end

    def destroy
      log_out
      redirect_to root_url
    end
  end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
  end
  def question
  end
  def reponse
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/la_page_secrete_helper.rb
module LaPageSecreteHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/la_page_secrete/about.html.erb
<%= link_to '/about' %>

app/views/la_page_secrete/contact.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link href="https://fonts.googleapis.com/css?family=Oswald:700|Patua+One|Roboto+Condensed:700" rel="stylesheet">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<section id="contact" class="content-section text-center">
        <div class="contact-section">
            <div class="container">
              <h2>Contact Us</h2>
              <p>Feel free to shout us by feeling the contact form or visiting our social network sites like Fackebook,Whatsapp,Twitter.</p>
              <div class="row">
                <div class="col-md-8 col-md-offset-2">
                  <form class="form-horizontal">
                    <div class="form-group">
                      <label for="exampleInputName2">Name</label>
                      <input type="text" class="form-control" id="exampleInputName2" placeholder="Jane Doe">
                    </div>
                    <div class="form-group">
                      <label for="exampleInputEmail2">Email</label>
                      <input type="email" class="form-control" id="exampleInputEmail2" placeholder="jane.doe@example.com">
                    </div>
                    <div class="form-group ">
                      <label for="exampleInputText">Your Message</label>
                     <textarea  class="form-control" placeholder="Description"></textarea>
                    </div>
                    <button type="submit" class="btn btn-default">Send Message</button>
                  </form>

                  <hr>
                    <h3>Our Social Sites</h3>
                  <ul class="list-inline banner-social-buttons">
                    <li><a href="#" class="btn btn-default btn-lg"><i class="fa fa-twitter"> <span class="network-name">Twitter</span></i></a></li>
                    <li><a href="#" class="btn btn-default btn-lg"><i class="fa fa-facebook"> <span class="network-name">Facebook</span></i></a></li>
                    <li><a href="#" class="btn btn-default btn-lg"><i class="fa fa-youtube-play"> <span class="network-name">Youtube</span></i></a></li>
                  </ul>
                </div>
              </div>
            </div>

app/views/la_page_secrete/create.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<h1> WELL DONE 😇</h1>
<p><%= @user.email %> voici la question qu'il faut toujours se poser</p>

<P> C'est quoi le le schmilblick </p>


<a href="/">Retour à la page d'accueil</a>

app/views/la_page_secrete/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>


  <body>
<br>
<br>
    <h1> YO Mouss! 😎</h1>
    <p> Question question du jour:
      Quelle est la question de l'univers?
      tu veux connaitre la réponse ?
    <p>Connecte-toi vite à ta session  :</p>

    <div class="row justify-content-center">

    <div class="col-lg-8">
    	<%= form_tag '/form_tag', method: "post" do %>


    		<div class="form-group">
    			<%= label_tag(:email, "Ton email :") %>
    			<%= email_field_tag(:email, nil, { class: 'form-control' }) %>
    		</div>

    		<div class="form-group">
    			<%= label_tag(:password, "MDP") %>
    			<%= text_area_tag(:password, nil , { rows: 1, class: 'form-control' } ) %>
    		</div>

    		<%= submit_tag("Connexion", class: 'btn btn-primary') %>

    	<% end %>
    </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <title>Secret</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "home",   '/' %></li>
            <li><%= link_to "help",   'help' %></li>
            <li><%= link_to "about", 'about' %></li>
            <li><%= link_to "contact", 'contact' %></li>
            <li><%= link_to "signup", '/users/new' %></li>
            <li><%= link_to "log_in", '/sessions/new' %></li>
          </ul>
        </nav>
      </div>
    </header>

  </head>

  <body>
    <%= yield %>

  </body>
</html>

app/views/layouts/header.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

  </head>
  <body>

  </body>
</html>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/shared/_error_message.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_page/home.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="style.css" type="text/css" media="screen"/>
    <title></title>
  </head>
  <body>

    <img src="/myheads.jpg" alt="background" />
    <div class="center jumbotron">
    <h1>Bienvenue Moussaillon !</h1>
    <h3>
      Tu peux te connecter sur ta session THP en toute sécurité 🎓
    </h3>
    <%= link_to "Rejoins-nous ici !", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
  </div>
  </body>
</html>

app/views/static_page/reponse.html.erb
<section class ='background'>


<br>
<br>
<br>
<br>
<br>
<br>
<h1 class="h1"> WELL DONE Mouss! 😇</h1>
<p class ="h1">Voici la réponse à la question de l'univers</p>

<P class='rep'>The schmilblick 😎</p>


<a href="/">Retour à la page d'accueil</a>
</section>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<br>
<br>
<br>
<br>



<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Sign up</h1>
    <%= form_for(@user) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<br>
<br>
<br>
<br>
<br>

<h1>Congrat!</h1>
 <p> Thank you <%= @user.email %></p>

<a href="/reponse">Découvre ici la réponse à la question de l'univers</a>